apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--dockerfile=Dockerfile"
    - "--context=https://github.com/pushdown99/jenkins-webhook.git"
    - "--context-sub-path=./simple-flask"
    - "--destination=ghcr.io/kmaster:hello"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
    env:
      - name: $
        valueFrom:
          secretKeyRef:
            name: github
            key: password
      - name: pushdown99
        valueFrom:
          secretKeyRef:
            name: github
            key: username
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json