apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kaniko.yaml
namespace: default
commonLabels:
  app: kaniko-debug
configMapGenerator:
- files:
  - Dockerfile
  name: kaniko-cm